// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_get_latest_image from "./routes/api/get-latest-image.ts";
import * as $api_process from "./routes/api/process.ts";
import * as $display from "./routes/display.tsx";
import * as $index from "./routes/index.tsx";
import * as $ImageViewer from "./islands/ImageViewer.tsx";
import * as $RecordAudio from "./islands/RecordAudio.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/get-latest-image.ts": $api_get_latest_image,
    "./routes/api/process.ts": $api_process,
    "./routes/display.tsx": $display,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ImageViewer.tsx": $ImageViewer,
    "./islands/RecordAudio.tsx": $RecordAudio,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
